/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package auditapp;


import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yaseen Ameer
 */
public class AI2 extends javax.swing.JFrame {
    int cb41a, cb42a, cb43a, cb44a, cb45a, cb46a, cb47a;
    int cb31b, cb32b, cb33b, cb34b, cb35b, cb36b, cb37b;
    int cb21c, cb22c, cb23c, cb24c, cb25c, cb26c, cb27c;
    int cb11d, cb12d, cb13d, cb14d, cb15d, cb16d, cb17d;
    
    
    int a, b, c, d, e;
    
    int a1,a2,a3,a4;
    
    double f;

    /**
     * Creates new form NewSignin
     */
    public AI2() {
        initComponents();
        this.setLocationRelativeTo(null);
      
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        label8 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel_inven11 = new javax.swing.JLabel();
        jLabel_inven15 = new javax.swing.JLabel();
        jLabel_inven16 = new javax.swing.JLabel();
        jLabel_inven22 = new javax.swing.JLabel();
        jLabel_inven23 = new javax.swing.JLabel();
        jLabel_inven27 = new javax.swing.JLabel();
        jLabel_inven28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_inven10 = new javax.swing.JLabel();
        jLabel_inven17 = new javax.swing.JLabel();
        jLabel_inven18 = new javax.swing.JLabel();
        jLabel_inven21 = new javax.swing.JLabel();
        jLabel_inven24 = new javax.swing.JLabel();
        jLabel_inven33 = new javax.swing.JLabel();
        jLabel_inven34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_inven38 = new javax.swing.JLabel();
        jLabel_inven40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_inven32 = new javax.swing.JLabel();
        jLabel_inven35 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_inven41 = new javax.swing.JLabel();
        jLabel_inven42 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_inven56 = new javax.swing.JLabel();
        test1 = new javax.swing.JTextField();
        test2 = new javax.swing.JTextField();
        test3 = new javax.swing.JTextField();
        test4 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel_inven53 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jPanel13 = new javax.swing.JPanel();
        jLabel_inven55 = new javax.swing.JLabel();
        test5 = new javax.swing.JTextField();
        cb11 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb41 = new javax.swing.JCheckBox();
        cb43 = new javax.swing.JCheckBox();
        cb33 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb45 = new javax.swing.JCheckBox();
        cb35 = new javax.swing.JCheckBox();
        cb25 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb46 = new javax.swing.JCheckBox();
        cb36 = new javax.swing.JCheckBox();
        cb26 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        cb44 = new javax.swing.JCheckBox();
        cb34 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb42 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        test6 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        test7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        cb47 = new javax.swing.JCheckBox();
        cb37 = new javax.swing.JCheckBox();
        cb27 = new javax.swing.JCheckBox();
        cb17 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jLabel_inven57 = new javax.swing.JLabel();

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox17.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label8.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 0, 620));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Acquire and Implement 2 (Acquire and Maintain Application Software)");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1180, 50));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Apakah System dapat melakukan pengolahan data dalam jumlah yang besar?");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1090, 50));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Menu");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 110, 40));

        jButton9.setBackground(new java.awt.Color(152, 201, 45));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(21, 25, 28));
        jButton9.setText("BACK");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, 190, 40));

        jLabel_inven11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven11.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven11.setText("1 .");
        jPanel1.add(jLabel_inven11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 50));

        jLabel_inven15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven15.setText("Apakah perancangan dan penerapan sistem aplikasi berdasarkan permintaan pengguna sesuai dengan kebijakan manajemen?");
        jPanel1.add(jLabel_inven15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1090, 50));

        jLabel_inven16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven16.setText("3 .");
        jPanel1.add(jLabel_inven16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 50));

        jLabel_inven22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven22.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven22.setText("Apakah sistem aplikasi yang diimplementasikan tidak menimbulkan masalah dan kerugian pada manajemen?");
        jPanel1.add(jLabel_inven22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 1090, 50));

        jLabel_inven23.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven23.setText("5 .");
        jPanel1.add(jLabel_inven23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 40, 50));

        jLabel_inven27.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven27.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven27.setText("Pemahaman pengguna dalam dalam mengoperasikan sistem aplikasi yang diimplementasikan?");
        jPanel1.add(jLabel_inven27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 1090, 50));

        jLabel_inven28.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven28.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven28.setText("7 .");
        jPanel1.add(jLabel_inven28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 40, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel_inven10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven10.setText("No");

        jLabel_inven17.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven17.setText("Pertanyaan");

        jLabel_inven18.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven18.setText("S");

        jLabel_inven21.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven21.setText("SS");

        jLabel_inven24.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven24.setText("KS");

        jLabel_inven33.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven33.setText("TS");

        jLabel_inven34.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven34.setText("Skala");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_inven10)
                .addGap(363, 363, 363)
                .addComponent(jLabel_inven17, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_inven21)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel_inven18)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel_inven24)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_inven33)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_inven34)
                        .addGap(85, 85, 85))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel_inven34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inven21)
                    .addComponent(jLabel_inven18)
                    .addComponent(jLabel_inven24)
                    .addComponent(jLabel_inven33)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inven10)
                    .addComponent(jLabel_inven17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1430, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven38.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven38.setText("Apakah dalam pengoperasian sistem aplikasi E-raport yang digunakan, pengguna tidak terjadi gangguan dan kesalahan?");

        jLabel_inven40.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven40.setText("2 .");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_inven38, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1140, 40));

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven32.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven32.setText("Apakah Sistem Aplikasi yang diimplementasikan sesuai dengan petunjuk yang ada?");

        jLabel_inven35.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven35.setText("4 .");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_inven32, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_inven35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1140, 40));

        jPanel8.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven41.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven41.setText("Apakah informasi yang ada pada sistem aplikasi merupakan informasi yang dibutuhkan pihak manajemen sesuai dengan proses bisnis?");

        jLabel_inven42.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven42.setText("6 .");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_inven41, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_inven42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1140, 40));

        jPanel9.setBackground(new java.awt.Color(0, 153, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven56.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven56.setText("Jumlah");
        jPanel9.add(jLabel_inven56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        test1.setBackground(new java.awt.Color(0, 204, 0));
        test1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test1.setText("0");
        test1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test1MouseMoved(evt);
            }
        });
        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test1MouseExited(evt);
            }
        });
        test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test1ActionPerformed(evt);
            }
        });
        jPanel9.add(test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        test2.setBackground(new java.awt.Color(0, 204, 0));
        test2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test2.setText("0");
        test2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test2MouseMoved(evt);
            }
        });
        test2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test2MouseExited(evt);
            }
        });
        test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2ActionPerformed(evt);
            }
        });
        jPanel9.add(test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 40));

        test3.setBackground(new java.awt.Color(0, 204, 0));
        test3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test3.setText("0");
        test3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test3MouseMoved(evt);
            }
        });
        test3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test3MouseExited(evt);
            }
        });
        test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test3ActionPerformed(evt);
            }
        });
        jPanel9.add(test3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 40, 40));

        test4.setBackground(new java.awt.Color(0, 204, 0));
        test4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test4.setText("0");
        test4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test4MouseMoved(evt);
            }
        });
        test4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test4MouseExited(evt);
            }
        });
        test4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test4ActionPerformed(evt);
            }
        });
        jPanel9.add(test4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 40, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1410, 40));

        jPanel12.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven53.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven53.setText("Jumlah Pertanyaan");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("7");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 955, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1250, 40));

        jPanel13.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven55.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven55.setText("Jumlah Nilai Jawaban");

        test5.setBackground(new java.awt.Color(0, 204, 0));
        test5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test5.setText("0");
        test5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test5MouseMoved(evt);
            }
        });
        test5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test5MouseExited(evt);
            }
        });
        test5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 941, Short.MAX_VALUE)
                .addComponent(test5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(test5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 1410, 40));

        cb11.setBackground(new java.awt.Color(0, 153, 102));
        cb11.setForeground(new java.awt.Color(255, 255, 0));
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        jPanel1.add(cb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 140, -1, -1));

        cb31.setBackground(new java.awt.Color(0, 153, 102));
        cb31.setForeground(new java.awt.Color(255, 255, 0));
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });
        jPanel1.add(cb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 140, -1, -1));

        cb21.setBackground(new java.awt.Color(0, 153, 102));
        cb21.setForeground(new java.awt.Color(255, 255, 0));
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });
        jPanel1.add(cb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 140, -1, -1));

        cb41.setBackground(new java.awt.Color(0, 153, 102));
        cb41.setForeground(new java.awt.Color(255, 255, 0));
        cb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb41ActionPerformed(evt);
            }
        });
        jPanel1.add(cb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 140, -1, -1));

        cb43.setBackground(new java.awt.Color(0, 153, 102));
        cb43.setForeground(new java.awt.Color(255, 255, 0));
        cb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb43ActionPerformed(evt);
            }
        });
        jPanel1.add(cb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 230, -1, -1));

        cb33.setBackground(new java.awt.Color(0, 153, 102));
        cb33.setForeground(new java.awt.Color(255, 255, 0));
        cb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb33ActionPerformed(evt);
            }
        });
        jPanel1.add(cb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 230, -1, -1));

        cb23.setBackground(new java.awt.Color(0, 153, 102));
        cb23.setForeground(new java.awt.Color(255, 255, 0));
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });
        jPanel1.add(cb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 230, -1, -1));

        cb13.setBackground(new java.awt.Color(0, 153, 102));
        cb13.setForeground(new java.awt.Color(255, 255, 0));
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });
        jPanel1.add(cb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, -1, -1));

        cb45.setBackground(new java.awt.Color(0, 153, 102));
        cb45.setForeground(new java.awt.Color(255, 255, 0));
        cb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb45ActionPerformed(evt);
            }
        });
        jPanel1.add(cb45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 320, -1, -1));

        cb35.setBackground(new java.awt.Color(0, 153, 102));
        cb35.setForeground(new java.awt.Color(255, 255, 0));
        cb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb35ActionPerformed(evt);
            }
        });
        jPanel1.add(cb35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, -1, -1));

        cb25.setBackground(new java.awt.Color(0, 153, 102));
        cb25.setForeground(new java.awt.Color(255, 255, 0));
        cb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb25ActionPerformed(evt);
            }
        });
        jPanel1.add(cb25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 320, -1, -1));

        cb15.setBackground(new java.awt.Color(0, 153, 102));
        cb15.setForeground(new java.awt.Color(255, 255, 0));
        cb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb15ActionPerformed(evt);
            }
        });
        jPanel1.add(cb15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 320, -1, -1));

        cb46.setBackground(new java.awt.Color(0, 153, 102));
        cb46.setForeground(new java.awt.Color(255, 255, 0));
        cb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb46ActionPerformed(evt);
            }
        });
        jPanel1.add(cb46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 360, -1, -1));

        cb36.setBackground(new java.awt.Color(0, 153, 102));
        cb36.setForeground(new java.awt.Color(255, 255, 0));
        cb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb36ActionPerformed(evt);
            }
        });
        jPanel1.add(cb36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 360, -1, -1));

        cb26.setBackground(new java.awt.Color(0, 153, 102));
        cb26.setForeground(new java.awt.Color(255, 255, 0));
        cb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb26ActionPerformed(evt);
            }
        });
        jPanel1.add(cb26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 360, -1, -1));

        cb16.setBackground(new java.awt.Color(0, 153, 102));
        cb16.setForeground(new java.awt.Color(255, 255, 0));
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });
        jPanel1.add(cb16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 360, -1, -1));

        cb44.setBackground(new java.awt.Color(0, 153, 102));
        cb44.setForeground(new java.awt.Color(255, 255, 0));
        cb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb44ActionPerformed(evt);
            }
        });
        jPanel1.add(cb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, -1, -1));

        cb34.setBackground(new java.awt.Color(0, 153, 102));
        cb34.setForeground(new java.awt.Color(255, 255, 0));
        cb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb34ActionPerformed(evt);
            }
        });
        jPanel1.add(cb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 270, -1, -1));

        cb24.setBackground(new java.awt.Color(0, 153, 102));
        cb24.setForeground(new java.awt.Color(255, 255, 0));
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });
        jPanel1.add(cb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 270, 20, -1));

        cb14.setBackground(new java.awt.Color(0, 153, 102));
        cb14.setForeground(new java.awt.Color(255, 255, 0));
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });
        jPanel1.add(cb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 270, -1, -1));

        cb42.setBackground(new java.awt.Color(0, 153, 102));
        cb42.setForeground(new java.awt.Color(255, 255, 0));
        cb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb42ActionPerformed(evt);
            }
        });
        jPanel1.add(cb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, -1, -1));

        cb32.setBackground(new java.awt.Color(0, 153, 102));
        cb32.setForeground(new java.awt.Color(255, 255, 0));
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });
        jPanel1.add(cb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 180, -1, -1));

        cb22.setBackground(new java.awt.Color(0, 153, 102));
        cb22.setForeground(new java.awt.Color(255, 255, 0));
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });
        jPanel1.add(cb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 180, -1, -1));

        cb12.setBackground(new java.awt.Color(0, 153, 102));
        cb12.setForeground(new java.awt.Color(255, 255, 0));
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });
        jPanel1.add(cb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        test6.setBackground(new java.awt.Color(0, 204, 0));
        test6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test6.setText("0");
        test6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test6MouseMoved(evt);
            }
        });
        test6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test6MouseExited(evt);
            }
        });
        test6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(test6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 500, 60, 40));

        jPanel11.setBackground(new java.awt.Color(102, 153, 0));

        test7.setBackground(new java.awt.Color(0, 204, 0));
        test7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test7.setText("Results");
        test7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test7MouseMoved(evt);
            }
        });
        test7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test7MouseExited(evt);
            }
        });
        test7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test7, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(test7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 430, 40));

        jButton10.setBackground(new java.awt.Color(152, 201, 45));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(21, 25, 28));
        jButton10.setText("NEXT");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 670, 190, 40));

        cb47.setBackground(new java.awt.Color(0, 153, 102));
        cb47.setForeground(new java.awt.Color(255, 255, 0));
        cb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb47ActionPerformed(evt);
            }
        });
        jPanel1.add(cb47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 400, -1, -1));

        cb37.setBackground(new java.awt.Color(0, 153, 102));
        cb37.setForeground(new java.awt.Color(255, 255, 0));
        cb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb37ActionPerformed(evt);
            }
        });
        jPanel1.add(cb37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 400, -1, -1));

        cb27.setBackground(new java.awt.Color(0, 153, 102));
        cb27.setForeground(new java.awt.Color(255, 255, 0));
        cb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb27ActionPerformed(evt);
            }
        });
        jPanel1.add(cb27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 400, -1, -1));

        cb17.setBackground(new java.awt.Color(0, 153, 102));
        cb17.setForeground(new java.awt.Color(255, 255, 0));
        cb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb17ActionPerformed(evt);
            }
        });
        jPanel1.add(cb17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 400, -1, -1));

        jPanel14.setBackground(new java.awt.Color(102, 153, 0));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("INDEKS =");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 500, 90, 40));

        jLabel_inven57.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven57.setForeground(new java.awt.Color(0, 153, 0));
        jLabel_inven57.setText("Maturity Level");
        jPanel1.add(jLabel_inven57, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PO9 fa = new PO9();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
       if(cb11.isSelected()){
            cb11d=1;
            cb11.setSelected(true);
        }else{
            cb11d=0;
            cb11.setSelected(false);
        }
    }//GEN-LAST:event_cb11ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
          
        if(cb31.isSelected()){
            cb31b=1;
            cb31.setSelected(true);
        }else{
            cb31b=0;
            cb31.setSelected(false);
        }
    }//GEN-LAST:event_cb31ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
        if(cb21.isSelected()){
            cb21c=1;
            cb21.setSelected(true);
        }else{
            cb21c=0;
            cb21.setSelected(false);
        }
    }//GEN-LAST:event_cb21ActionPerformed

    private void cb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb41ActionPerformed
        
        if(cb41.isSelected()){
            cb41a=1;
            cb41.setSelected(true);
        }else{
            cb41a=0;
            cb41.setSelected(false);
        }
    }//GEN-LAST:event_cb41ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void cb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb43ActionPerformed
          if(cb43.isSelected()){
            cb43a=1;
            cb43.setSelected(true);
        }else{
            cb43a=0;
            cb43.setSelected(false);
        }
    }//GEN-LAST:event_cb43ActionPerformed

    private void cb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb33ActionPerformed
          if(cb33.isSelected()){
            cb33b=1;
            cb33.setSelected(true);
        }else{
            cb33b=0;
            cb33.setSelected(false);
        }
    }//GEN-LAST:event_cb33ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
            if(cb23.isSelected()){
            cb23c=1;
            cb23.setSelected(true);
        }else{
            cb23c=0;
            cb23.setSelected(false);
        }
    }//GEN-LAST:event_cb23ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
         if(cb13.isSelected()){
            cb13d=1;
            cb13.setSelected(true);
        }else{
            cb13d=0;
            cb13.setSelected(false);
        }
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb45ActionPerformed
        if(cb45.isSelected()){
            cb45a=1;
            cb45.setSelected(true);
        }else{
            cb45a=0;
            cb45.setSelected(false);
        }
    }//GEN-LAST:event_cb45ActionPerformed

    private void cb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb35ActionPerformed
          if(cb35.isSelected()){
            cb35b=1;
            cb35.setSelected(true);
        }else{
            cb35b=0;
            cb35.setSelected(false);
        }
    }//GEN-LAST:event_cb35ActionPerformed

    private void cb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb25ActionPerformed
             if(cb25.isSelected()){
            cb25c=1;
            cb25.setSelected(true);
        }else{
            cb25c=0;
            cb25.setSelected(false);
        }
    }//GEN-LAST:event_cb25ActionPerformed

    private void cb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb15ActionPerformed
         if(cb15.isSelected()){
            cb15d=1;
            cb15.setSelected(true);
        }else{
            cb15d=0;
            cb15.setSelected(false);
        }
    }//GEN-LAST:event_cb15ActionPerformed

    private void cb46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb46ActionPerformed
        if(cb46.isSelected()){
            cb46a=1;
            cb46.setSelected(true);
        }else{
            cb46a=0;
            cb46.setSelected(false);
        }
    }//GEN-LAST:event_cb46ActionPerformed

    private void cb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb36ActionPerformed
          if(cb36.isSelected()){
            cb36b=1;
            cb36.setSelected(true);
        }else{
            cb36b=0;
            cb36.setSelected(false);
        }
    }//GEN-LAST:event_cb36ActionPerformed

    private void cb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb26ActionPerformed
             if(cb26.isSelected()){
            cb26c=1;
            cb26.setSelected(true);
        }else{
            cb26c=0;
            cb26.setSelected(false);
        }
    }//GEN-LAST:event_cb26ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
         if(cb16.isSelected()){
            cb16d=1;
            cb16.setSelected(true);
        }else{
            cb16d=0;
            cb16.setSelected(false);
        }
    }//GEN-LAST:event_cb16ActionPerformed

    private void cb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb44ActionPerformed
         if(cb44.isSelected()){
            cb44a=1;
            cb44.setSelected(true);
        }else{
            cb44a=0;
            cb44.setSelected(false);
        }
    }//GEN-LAST:event_cb44ActionPerformed

    private void cb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb34ActionPerformed
         if(cb34.isSelected()){
            cb34b=1;
            cb34.setSelected(true);
        }else{
            cb34b=0;
            cb34.setSelected(false);
        }
    }//GEN-LAST:event_cb34ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
             if(cb24.isSelected()){
            cb24c=1;
            cb24.setSelected(true);
        }else{
            cb24c=0;
            cb24.setSelected(false);
        }
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
         if(cb14.isSelected()){
            cb14d=1;
            cb14.setSelected(true);
        }else{
            cb14d=0;
            cb14.setSelected(false);
        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb42ActionPerformed
         if(cb42.isSelected()){
            cb42a=1;
            cb42.setSelected(true);
        }else{
            cb42a=0;
            cb42.setSelected(false);
        }
    }//GEN-LAST:event_cb42ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
         if(cb32.isSelected()){
            cb32b=1;
            cb32.setSelected(true);
        }else{
            cb32b=0;
            cb32.setSelected(false);
        }
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        if(cb22.isSelected()){
            cb22c=1;
            cb22.setSelected(true);
        }else{
            cb22c=0;
            cb22.setSelected(false);
        }
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
         if(cb12.isSelected()){
            cb12d=1;
            cb12.setSelected(true);
        }else{
            cb12d=0;
            cb12.setSelected(false);
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cb47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb47ActionPerformed
        if(cb47.isSelected()){
            cb47a=1;
            cb47.setSelected(true);
        }else{
            cb47a=0;
            cb47.setSelected(false);
        }
    }//GEN-LAST:event_cb47ActionPerformed

    private void cb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb37ActionPerformed
          if(cb37.isSelected()){
            cb37b=1;
            cb37.setSelected(true);
        }else{
            cb37b=0;
            cb37.setSelected(false);
        }
    }//GEN-LAST:event_cb37ActionPerformed

    private void cb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb27ActionPerformed
             if(cb27.isSelected()){
            cb27c=1;
            cb27.setSelected(true);
        }else{
            cb27c=0;
            cb27.setSelected(false);
        }
    }//GEN-LAST:event_cb27ActionPerformed

    private void cb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb17ActionPerformed
         if(cb17.isSelected()){
            cb17d=1;
            cb17.setSelected(true);
        }else{
            cb17d=0;
            cb17.setSelected(false);
        }
    }//GEN-LAST:event_cb17ActionPerformed

    private void test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test1ActionPerformed
       
    }//GEN-LAST:event_test1ActionPerformed

    private void test1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseExited
     
        a = cb41a+cb42a+cb43a+cb44a+cb45a+cb46a+cb47a;
        a1 = a * 4;
        
        test1.setText(Integer.toString(a));
    }//GEN-LAST:event_test1MouseExited

    private void test1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseMoved
        
    }//GEN-LAST:event_test1MouseMoved

    private void test2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test2MouseMoved

    private void test2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseExited
       int b;
        b = cb31b+cb32b+cb33b+cb34b+cb35b+cb36b+cb37b;
        a2 = b*3;
        test2.setText(Integer.toString(b));
    }//GEN-LAST:event_test2MouseExited

    private void test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test2ActionPerformed

    private void test3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test3MouseMoved

    private void test3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseExited
        int c;
        c = cb21c+cb22c+cb23c+cb24c+cb25c+cb26c+cb27c;
        a3=c*2;
        test3.setText(Integer.toString(c));
    }//GEN-LAST:event_test3MouseExited

    private void test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test3ActionPerformed

    private void test4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test4MouseMoved

    private void test4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseExited
         int d;
        d = cb11d+cb12d+cb13d+cb14d+cb15d+cb16d+cb17d;
        a4 = d*1;
        test4.setText(Integer.toString(d));
    }//GEN-LAST:event_test4MouseExited

    private void test4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test4ActionPerformed

    private void test5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test5MouseMoved

    private void test5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test5MouseExited
       
        
        e=a1+a2+a3+a4;
        
        test5.setText(Integer.toString(e));
    }//GEN-LAST:event_test5MouseExited

    private void test5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test5ActionPerformed
        
    }//GEN-LAST:event_test5ActionPerformed

    private void test6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test6MouseMoved

    private void test6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test6MouseExited
        double f;
        f = e/7;
        
        test6.setText(Double.toString(f));
        
        if (f < 0.5){
            test7.setText("Non Existent");
        }else{
            if(f >0.52 && f <1.5){
                test7.setText("Intial/Ad Hoc");
            }else{
                if(f >1.51 && f<2.5){
                    test7.setText("Repeatable but Intuitive");
                }else{
                    if(f>2.51 && f<3.50){
                        test7.setText("Defined Process");
                    }else{
                        if(f>3.51 && f<4.5){
                            test7.setText("Managed And Measurable");
                        }else{
                            if(f>4.51){
                                test7.setText("Optimized");
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_test6MouseExited

    private void test6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test6ActionPerformed

    private void test7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test7MouseMoved

    private void test7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseExited
        
    }//GEN-LAST:event_test7MouseExited

    private void test7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb17;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb25;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb27;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb33;
    private javax.swing.JCheckBox cb34;
    private javax.swing.JCheckBox cb35;
    private javax.swing.JCheckBox cb36;
    private javax.swing.JCheckBox cb37;
    private javax.swing.JCheckBox cb41;
    private javax.swing.JCheckBox cb42;
    private javax.swing.JCheckBox cb43;
    private javax.swing.JCheckBox cb44;
    private javax.swing.JCheckBox cb45;
    private javax.swing.JCheckBox cb46;
    private javax.swing.JCheckBox cb47;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel_inven10;
    private javax.swing.JLabel jLabel_inven11;
    private javax.swing.JLabel jLabel_inven15;
    private javax.swing.JLabel jLabel_inven16;
    private javax.swing.JLabel jLabel_inven17;
    private javax.swing.JLabel jLabel_inven18;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven21;
    private javax.swing.JLabel jLabel_inven22;
    private javax.swing.JLabel jLabel_inven23;
    private javax.swing.JLabel jLabel_inven24;
    private javax.swing.JLabel jLabel_inven27;
    private javax.swing.JLabel jLabel_inven28;
    private javax.swing.JLabel jLabel_inven32;
    private javax.swing.JLabel jLabel_inven33;
    private javax.swing.JLabel jLabel_inven34;
    private javax.swing.JLabel jLabel_inven35;
    private javax.swing.JLabel jLabel_inven38;
    private javax.swing.JLabel jLabel_inven40;
    private javax.swing.JLabel jLabel_inven41;
    private javax.swing.JLabel jLabel_inven42;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JLabel jLabel_inven53;
    private javax.swing.JLabel jLabel_inven55;
    private javax.swing.JLabel jLabel_inven56;
    private javax.swing.JLabel jLabel_inven57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label8;
    private javax.swing.JTextField test1;
    private javax.swing.JTextField test2;
    private javax.swing.JTextField test3;
    private javax.swing.JTextField test4;
    private javax.swing.JTextField test5;
    private javax.swing.JTextField test6;
    private javax.swing.JTextField test7;
    // End of variables declaration//GEN-END:variables
}
