/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package auditapp;


import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yaseen Ameer
 */
public class ME2 extends javax.swing.JFrame {
    int cb41a, cb42a, cb43a, cb44a, cb45a, cb46a, cb47a;
    int cb31b, cb32b, cb33b, cb34b, cb35b, cb36b, cb37b;
    int cb21c, cb22c, cb23c, cb24c, cb25c, cb26c, cb27c;
    int cb11d, cb12d, cb13d, cb14d, cb15d, cb16d, cb17d;
    
    
    int a, b, c, d, e;
   
    
    int a1,a2,a3,a4;
    

    double f;

    /**
     * Creates new form NewSignin
     */
    public ME2(String jaci, String iaci, String aa, String bb) {
        initComponents();
        this.setLocationRelativeTo(null);
      
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        y1.setText(jaci);
        y2.setText(iaci);
        
        y3.setText(aa);
        y4.setText(bb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        label8 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel_inven11 = new javax.swing.JLabel();
        jLabel_inven15 = new javax.swing.JLabel();
        jLabel_inven16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_inven10 = new javax.swing.JLabel();
        jLabel_inven17 = new javax.swing.JLabel();
        jLabel_inven18 = new javax.swing.JLabel();
        jLabel_inven21 = new javax.swing.JLabel();
        jLabel_inven24 = new javax.swing.JLabel();
        jLabel_inven33 = new javax.swing.JLabel();
        jLabel_inven34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_inven38 = new javax.swing.JLabel();
        jLabel_inven40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_inven32 = new javax.swing.JLabel();
        jLabel_inven35 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_inven56 = new javax.swing.JLabel();
        test1 = new javax.swing.JTextField();
        test2 = new javax.swing.JTextField();
        test3 = new javax.swing.JTextField();
        test4 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel_inven53 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jPanel13 = new javax.swing.JPanel();
        jLabel_inven55 = new javax.swing.JLabel();
        jme = new javax.swing.JTextField();
        cb11 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb41 = new javax.swing.JCheckBox();
        cb43 = new javax.swing.JCheckBox();
        cb33 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb44 = new javax.swing.JCheckBox();
        cb34 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb42 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        ime = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        test7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jLabel_inven57 = new javax.swing.JLabel();
        y2 = new javax.swing.JTextField();
        y1 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        y4 = new javax.swing.JTextField();

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox17.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label8.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 0, 620));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Monitor and Evaluate 2 (Monitor and Evaluate Internal Control)");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1180, 50));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Apakah pengendalian dilakukan oleh pihak manajemen terhadap sistem aplikasi secara ruti?");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1090, 50));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Menu");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 40));

        jLabel_inven11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven11.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven11.setText("1 .");
        jPanel1.add(jLabel_inven11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 50));

        jLabel_inven15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven15.setText("Apakah Informasi yang dihasilkan oleh Sistem Aplikasi akan Dievaluasi oleh pihak manajemen?");
        jPanel1.add(jLabel_inven15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1090, 50));

        jLabel_inven16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven16.setText("3 .");
        jPanel1.add(jLabel_inven16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel_inven10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven10.setText("No");

        jLabel_inven17.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven17.setText("Pertanyaan");

        jLabel_inven18.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven18.setText("S");

        jLabel_inven21.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven21.setText("SS");

        jLabel_inven24.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven24.setText("KS");

        jLabel_inven33.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven33.setText("TS");

        jLabel_inven34.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven34.setText("Bobot");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_inven10)
                .addGap(363, 363, 363)
                .addComponent(jLabel_inven17, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_inven21)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel_inven18)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel_inven24)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_inven33)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_inven34)
                        .addGap(85, 85, 85))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel_inven34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inven21)
                    .addComponent(jLabel_inven18)
                    .addComponent(jLabel_inven24)
                    .addComponent(jLabel_inven33)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inven10)
                    .addComponent(jLabel_inven17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1430, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven38.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven38.setText("Apakah pihak manajemen melakukan pengawasan terhadap pengunaan sistem aplikasi?");

        jLabel_inven40.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven40.setText("2 .");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_inven38, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1140, 40));

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven32.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven32.setText("Apakah dalam penanganan masalah yang terjadi pada sistem aplikasi, pihak pengembang turut serta menangani masalah kontrol sistem?");

        jLabel_inven35.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven35.setText("4 .");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_inven32, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_inven35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_inven32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1140, 40));

        jPanel9.setBackground(new java.awt.Color(0, 153, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven56.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven56.setText("Jumlah");
        jPanel9.add(jLabel_inven56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        test1.setBackground(new java.awt.Color(0, 204, 0));
        test1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test1.setText("0");
        test1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test1MouseMoved(evt);
            }
        });
        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test1MouseExited(evt);
            }
        });
        test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test1ActionPerformed(evt);
            }
        });
        jPanel9.add(test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        test2.setBackground(new java.awt.Color(0, 204, 0));
        test2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test2.setText("0");
        test2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test2MouseMoved(evt);
            }
        });
        test2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test2MouseExited(evt);
            }
        });
        test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2ActionPerformed(evt);
            }
        });
        jPanel9.add(test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 40));

        test3.setBackground(new java.awt.Color(0, 204, 0));
        test3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test3.setText("0");
        test3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test3MouseMoved(evt);
            }
        });
        test3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test3MouseExited(evt);
            }
        });
        test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test3ActionPerformed(evt);
            }
        });
        jPanel9.add(test3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 40, 40));

        test4.setBackground(new java.awt.Color(0, 204, 0));
        test4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test4.setText("0");
        test4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test4MouseMoved(evt);
            }
        });
        test4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test4MouseExited(evt);
            }
        });
        test4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test4ActionPerformed(evt);
            }
        });
        jPanel9.add(test4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 40, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 1420, 40));

        jPanel12.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven53.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven53.setText("Jumlah Pertanyaan");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("4");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 955, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1250, 40));

        jPanel13.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven55.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven55.setText("Jumlah Nilai Jawaban");

        jme.setBackground(new java.awt.Color(0, 204, 0));
        jme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jme.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jme.setText("0");
        jme.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmeMouseMoved(evt);
            }
        });
        jme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmeMouseExited(evt);
            }
        });
        jme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 925, Short.MAX_VALUE)
                .addComponent(jme, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1420, 40));

        cb11.setBackground(new java.awt.Color(0, 153, 102));
        cb11.setForeground(new java.awt.Color(255, 255, 0));
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        jPanel1.add(cb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 140, -1, -1));

        cb31.setBackground(new java.awt.Color(0, 153, 102));
        cb31.setForeground(new java.awt.Color(255, 255, 0));
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });
        jPanel1.add(cb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 140, -1, -1));

        cb21.setBackground(new java.awt.Color(0, 153, 102));
        cb21.setForeground(new java.awt.Color(255, 255, 0));
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });
        jPanel1.add(cb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 140, -1, -1));

        cb41.setBackground(new java.awt.Color(0, 153, 102));
        cb41.setForeground(new java.awt.Color(255, 255, 0));
        cb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb41ActionPerformed(evt);
            }
        });
        jPanel1.add(cb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 140, -1, -1));

        cb43.setBackground(new java.awt.Color(0, 153, 102));
        cb43.setForeground(new java.awt.Color(255, 255, 0));
        cb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb43ActionPerformed(evt);
            }
        });
        jPanel1.add(cb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 230, -1, -1));

        cb33.setBackground(new java.awt.Color(0, 153, 102));
        cb33.setForeground(new java.awt.Color(255, 255, 0));
        cb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb33ActionPerformed(evt);
            }
        });
        jPanel1.add(cb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 230, -1, -1));

        cb23.setBackground(new java.awt.Color(0, 153, 102));
        cb23.setForeground(new java.awt.Color(255, 255, 0));
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });
        jPanel1.add(cb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 230, -1, -1));

        cb13.setBackground(new java.awt.Color(0, 153, 102));
        cb13.setForeground(new java.awt.Color(255, 255, 0));
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });
        jPanel1.add(cb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, -1, -1));

        cb44.setBackground(new java.awt.Color(0, 153, 102));
        cb44.setForeground(new java.awt.Color(255, 255, 0));
        cb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb44ActionPerformed(evt);
            }
        });
        jPanel1.add(cb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, -1, -1));

        cb34.setBackground(new java.awt.Color(0, 153, 102));
        cb34.setForeground(new java.awt.Color(255, 255, 0));
        cb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb34ActionPerformed(evt);
            }
        });
        jPanel1.add(cb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 270, -1, -1));

        cb24.setBackground(new java.awt.Color(0, 153, 102));
        cb24.setForeground(new java.awt.Color(255, 255, 0));
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });
        jPanel1.add(cb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 270, 20, -1));

        cb14.setBackground(new java.awt.Color(0, 153, 102));
        cb14.setForeground(new java.awt.Color(255, 255, 0));
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });
        jPanel1.add(cb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 270, -1, -1));

        cb42.setBackground(new java.awt.Color(0, 153, 102));
        cb42.setForeground(new java.awt.Color(255, 255, 0));
        cb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb42ActionPerformed(evt);
            }
        });
        jPanel1.add(cb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, -1, -1));

        cb32.setBackground(new java.awt.Color(0, 153, 102));
        cb32.setForeground(new java.awt.Color(255, 255, 0));
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });
        jPanel1.add(cb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 180, -1, -1));

        cb22.setBackground(new java.awt.Color(0, 153, 102));
        cb22.setForeground(new java.awt.Color(255, 255, 0));
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });
        jPanel1.add(cb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 180, -1, -1));

        cb12.setBackground(new java.awt.Color(0, 153, 102));
        cb12.setForeground(new java.awt.Color(255, 255, 0));
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });
        jPanel1.add(cb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        ime.setBackground(new java.awt.Color(0, 204, 0));
        ime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ime.setText("0");
        ime.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                imeMouseMoved(evt);
            }
        });
        ime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imeMouseExited(evt);
            }
        });
        ime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ime, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 380, 80, 40));

        jPanel11.setBackground(new java.awt.Color(102, 153, 0));

        test7.setBackground(new java.awt.Color(0, 204, 0));
        test7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test7.setText("Results");
        test7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test7MouseMoved(evt);
            }
        });
        test7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test7MouseExited(evt);
            }
        });
        test7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test7, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(test7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 480, 430, 40));

        jButton10.setBackground(new java.awt.Color(152, 201, 45));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(21, 25, 28));
        jButton10.setText("NEXT");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 530, 190, 40));

        jPanel14.setBackground(new java.awt.Color(102, 153, 0));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("INDEKS =");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 380, 90, 40));

        jLabel_inven57.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven57.setForeground(new java.awt.Color(0, 153, 0));
        jLabel_inven57.setText("Maturity Level");
        jPanel1.add(jLabel_inven57, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, -1));

        y2.setBackground(new java.awt.Color(0, 0, 0));
        y2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y2.setText("0");
        y2.setBorder(null);
        y2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                y2MouseMoved(evt);
            }
        });
        y2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                y2MouseExited(evt);
            }
        });
        y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2ActionPerformed(evt);
            }
        });
        jPanel1.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 530, 40, 30));

        y1.setBackground(new java.awt.Color(0, 0, 0));
        y1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y1.setText("0");
        y1.setBorder(null);
        y1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                y1MouseMoved(evt);
            }
        });
        y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                y1MouseExited(evt);
            }
        });
        y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1ActionPerformed(evt);
            }
        });
        jPanel1.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 530, 40, 30));

        y3.setBackground(new java.awt.Color(0, 0, 0));
        y3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y3.setText("0");
        y3.setBorder(null);
        y3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                y3MouseMoved(evt);
            }
        });
        y3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                y3MouseExited(evt);
            }
        });
        y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3ActionPerformed(evt);
            }
        });
        jPanel1.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 530, 40, 30));

        y4.setBackground(new java.awt.Color(0, 0, 0));
        y4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        y4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y4.setText("0");
        y4.setBorder(null);
        y4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                y4MouseMoved(evt);
            }
        });
        y4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                y4MouseExited(evt);
            }
        });
        y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y4ActionPerformed(evt);
            }
        });
        jPanel1.add(y4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
       if(cb11.isSelected()){
            cb11d=1;
            cb11.setSelected(true);
        }else{
            cb11d=0;
            cb11.setSelected(false);
        }
    }//GEN-LAST:event_cb11ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
          
        if(cb31.isSelected()){
            cb31b=1;
            cb31.setSelected(true);
        }else{
            cb31b=0;
            cb31.setSelected(false);
        }
    }//GEN-LAST:event_cb31ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
        if(cb21.isSelected()){
            cb21c=1;
            cb21.setSelected(true);
        }else{
            cb21c=0;
            cb21.setSelected(false);
        }
    }//GEN-LAST:event_cb21ActionPerformed

    private void cb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb41ActionPerformed
        
        if(cb41.isSelected()){
            cb41a=1;
            cb41.setSelected(true);
        }else{
            cb41a=0;
            cb41.setSelected(false);
        }
    }//GEN-LAST:event_cb41ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void cb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb43ActionPerformed
          if(cb43.isSelected()){
            cb43a=1;
            cb43.setSelected(true);
        }else{
            cb43a=0;
            cb43.setSelected(false);
        }
    }//GEN-LAST:event_cb43ActionPerformed

    private void cb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb33ActionPerformed
          if(cb33.isSelected()){
            cb33b=1;
            cb33.setSelected(true);
        }else{
            cb33b=0;
            cb33.setSelected(false);
        }
    }//GEN-LAST:event_cb33ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
            if(cb23.isSelected()){
            cb23c=1;
            cb23.setSelected(true);
        }else{
            cb23c=0;
            cb23.setSelected(false);
        }
    }//GEN-LAST:event_cb23ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
         if(cb13.isSelected()){
            cb13d=1;
            cb13.setSelected(true);
        }else{
            cb13d=0;
            cb13.setSelected(false);
        }
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb44ActionPerformed
         if(cb44.isSelected()){
            cb44a=1;
            cb44.setSelected(true);
        }else{
            cb44a=0;
            cb44.setSelected(false);
        }
    }//GEN-LAST:event_cb44ActionPerformed

    private void cb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb34ActionPerformed
         if(cb34.isSelected()){
            cb34b=1;
            cb34.setSelected(true);
        }else{
            cb34b=0;
            cb34.setSelected(false);
        }
    }//GEN-LAST:event_cb34ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
             if(cb24.isSelected()){
            cb24c=1;
            cb24.setSelected(true);
        }else{
            cb24c=0;
            cb24.setSelected(false);
        }
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
         if(cb14.isSelected()){
            cb14d=1;
            cb14.setSelected(true);
        }else{
            cb14d=0;
            cb14.setSelected(false);
        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb42ActionPerformed
         if(cb42.isSelected()){
            cb42a=1;
            cb42.setSelected(true);
        }else{
            cb42a=0;
            cb42.setSelected(false);
        }
    }//GEN-LAST:event_cb42ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
         if(cb32.isSelected()){
            cb32b=1;
            cb32.setSelected(true);
        }else{
            cb32b=0;
            cb32.setSelected(false);
        }
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        if(cb22.isSelected()){
            cb22c=1;
            cb22.setSelected(true);
        }else{
            cb22c=0;
            cb22.setSelected(false);
        }
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
         if(cb12.isSelected()){
            cb12d=1;
            cb12.setSelected(true);
        }else{
            cb12d=0;
            cb12.setSelected(false);
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DS5 fa = new DS5(jme.getText(),ime.getText(),y1.getText(),y2.getText(),y3.getText(),y4.getText());
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test1ActionPerformed
       
    }//GEN-LAST:event_test1ActionPerformed

    private void test1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseExited
     
        a = cb41a+cb42a+cb43a+cb44a;
        a1 = a * 4;
        
        test1.setText(Integer.toString(a));
    }//GEN-LAST:event_test1MouseExited

    private void test1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseMoved
        
    }//GEN-LAST:event_test1MouseMoved

    private void test2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test2MouseMoved

    private void test2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseExited
       int b;
        b = cb31b+cb32b+cb33b+cb34b;
        a2 = b*3;
        test2.setText(Integer.toString(b));
    }//GEN-LAST:event_test2MouseExited

    private void test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test2ActionPerformed

    private void test3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test3MouseMoved

    private void test3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseExited
        int c;
        c = cb21c+cb22c+cb23c+cb24c;
        a3=c*2;
        test3.setText(Integer.toString(c));
    }//GEN-LAST:event_test3MouseExited

    private void test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test3ActionPerformed

    private void test4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test4MouseMoved

    private void test4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseExited
         int d;
        d = cb11d+cb12d+cb13d+cb14d;
        a4 = d*1;
        test4.setText(Integer.toString(d));
    }//GEN-LAST:event_test4MouseExited

    private void test4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test4ActionPerformed

    private void jmeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jmeMouseMoved

    private void jmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmeMouseExited
       
        
        e=a1+a2+a3+a4;
        
        jme.setText(Integer.toString(e));
    }//GEN-LAST:event_jmeMouseExited

    private void jmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeActionPerformed
        
    }//GEN-LAST:event_jmeActionPerformed

    private void imeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_imeMouseMoved

    private void imeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imeMouseExited
        DecimalFormat formatData = new DecimalFormat("#.##");
       double y;
       
       y=(double)e/4;
       
        f = Double.valueOf(formatData.format(y));
        ime.setText(Double.toString(f));
        
        if (f < 0.5){
            test7.setText("Non Existent");
        }else{
            if(f >0.52 && f <1.5){
                test7.setText("Intial/Ad Hoc");
            }else{
                if(f >1.51 && f<2.5){
                    test7.setText("Repeatable but Intuitive");
                }else{
                    if(f>2.51 && f<3.50){
                        test7.setText("Defined Process");
                    }else{
                        if(f>3.51 && f<4.5){
                            test7.setText("Managed And Measurable");
                        }else{
                            if(f>4.51){
                                test7.setText("Optimized");
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_imeMouseExited

    private void imeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeActionPerformed

    private void test7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test7MouseMoved

    private void test7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseExited
        
    }//GEN-LAST:event_test7MouseExited

    private void test7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test7ActionPerformed

    private void y2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_y2MouseMoved

    private void y2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_y2MouseExited

    private void y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2ActionPerformed

    private void y1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_y1MouseMoved

    private void y1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_y1MouseExited

    private void y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1ActionPerformed

    private void y3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_y3MouseMoved

    private void y3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_y3MouseExited

    private void y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3ActionPerformed

    private void y4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_y4MouseMoved

    private void y4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_y4MouseExited

    private void y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb33;
    private javax.swing.JCheckBox cb34;
    private javax.swing.JCheckBox cb41;
    private javax.swing.JCheckBox cb42;
    private javax.swing.JCheckBox cb43;
    private javax.swing.JCheckBox cb44;
    private javax.swing.JTextField ime;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel_inven10;
    private javax.swing.JLabel jLabel_inven11;
    private javax.swing.JLabel jLabel_inven15;
    private javax.swing.JLabel jLabel_inven16;
    private javax.swing.JLabel jLabel_inven17;
    private javax.swing.JLabel jLabel_inven18;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven21;
    private javax.swing.JLabel jLabel_inven24;
    private javax.swing.JLabel jLabel_inven32;
    private javax.swing.JLabel jLabel_inven33;
    private javax.swing.JLabel jLabel_inven34;
    private javax.swing.JLabel jLabel_inven35;
    private javax.swing.JLabel jLabel_inven38;
    private javax.swing.JLabel jLabel_inven40;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JLabel jLabel_inven53;
    private javax.swing.JLabel jLabel_inven55;
    private javax.swing.JLabel jLabel_inven56;
    private javax.swing.JLabel jLabel_inven57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jme;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label8;
    private javax.swing.JTextField test1;
    private javax.swing.JTextField test2;
    private javax.swing.JTextField test3;
    private javax.swing.JTextField test4;
    private javax.swing.JTextField test7;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField y4;
    // End of variables declaration//GEN-END:variables
}
