/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package auditapp;


import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yaseen Ameer
 */
public class PO9 extends javax.swing.JFrame {
    int cb51a, cb52a, cb53a, cb54a, cb55a, cb56a, cb57a, cb58a;
    int cb41a, cb42a, cb43a, cb44a, cb45a, cb46a, cb47a, cb48a;
    int cb31b, cb32b, cb33b, cb34b, cb35b, cb36b, cb37b, cb38b;
    int cb21c, cb22c, cb23c, cb24c, cb25c, cb26c, cb27c, cb28c;
    int cb11d, cb12d, cb13d, cb14d, cb15d, cb16d, cb17d, cb18d;
    
    
    int a, b, c, d, e,g;
    
    int a1,a2,a3,a4,a5;
    
    double f;

    /**
     * Creates new form NewSignin
     */
    public PO9() {
        initComponents();
        this.setLocationRelativeTo(null);
      
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        label8 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel_inven11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_inven59 = new javax.swing.JLabel();
        jLabel_inven60 = new javax.swing.JLabel();
        jLabel_inven61 = new javax.swing.JLabel();
        jLabel_inven62 = new javax.swing.JLabel();
        jLabel_inven63 = new javax.swing.JLabel();
        jLabel_inven64 = new javax.swing.JLabel();
        jLabel_inven65 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_inven40 = new javax.swing.JLabel();
        jLabel_inven43 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_inven56 = new javax.swing.JLabel();
        test1 = new javax.swing.JTextField();
        test2 = new javax.swing.JTextField();
        test3 = new javax.swing.JTextField();
        test4 = new javax.swing.JTextField();
        test5 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel_inven53 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jPanel13 = new javax.swing.JPanel();
        jLabel_inven55 = new javax.swing.JLabel();
        jpo = new javax.swing.JTextField();
        cb11 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb41 = new javax.swing.JCheckBox();
        cb43 = new javax.swing.JCheckBox();
        cb33 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb45 = new javax.swing.JCheckBox();
        cb35 = new javax.swing.JCheckBox();
        cb25 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb46 = new javax.swing.JCheckBox();
        cb36 = new javax.swing.JCheckBox();
        cb26 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        cb44 = new javax.swing.JCheckBox();
        cb34 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb42 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        ipo = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        test7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        cb47 = new javax.swing.JCheckBox();
        cb37 = new javax.swing.JCheckBox();
        cb27 = new javax.swing.JCheckBox();
        cb17 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jLabel_inven57 = new javax.swing.JLabel();
        jLabel_inven6 = new javax.swing.JLabel();
        jLabel_inven12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_inven44 = new javax.swing.JLabel();
        jLabel_inven45 = new javax.swing.JLabel();
        jLabel_inven46 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel_inven47 = new javax.swing.JLabel();
        jLabel_inven48 = new javax.swing.JLabel();
        jLabel_inven49 = new javax.swing.JLabel();
        jLabel_inven7 = new javax.swing.JLabel();
        jLabel_inven13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel_inven50 = new javax.swing.JLabel();
        jLabel_inven51 = new javax.swing.JLabel();
        jLabel_inven8 = new javax.swing.JLabel();
        jLabel_inven14 = new javax.swing.JLabel();
        jLabel_inven9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_inven52 = new javax.swing.JLabel();
        jLabel_inven54 = new javax.swing.JLabel();
        jLabel_inven58 = new javax.swing.JLabel();
        cb48 = new javax.swing.JCheckBox();
        cb38 = new javax.swing.JCheckBox();
        cb28 = new javax.swing.JCheckBox();
        cb18 = new javax.swing.JCheckBox();
        cb51 = new javax.swing.JCheckBox();
        cb52 = new javax.swing.JCheckBox();
        cb53 = new javax.swing.JCheckBox();
        cb54 = new javax.swing.JCheckBox();
        cb55 = new javax.swing.JCheckBox();
        cb56 = new javax.swing.JCheckBox();
        cb57 = new javax.swing.JCheckBox();
        cb58 = new javax.swing.JCheckBox();

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setBackground(new java.awt.Color(0, 153, 102));
        jCheckBox17.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label8.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 0, 620));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Plan And Organize 9 (assess and managae IT Risk)");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1180, 50));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven5.setText("Apakah pembuatan suatu framework penilaian resiko yang sistematis telah membantu dalam mencapai tujuan bisnis?");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1090, 50));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Menu");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, 110, 40));

        jLabel_inven11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven11.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven11.setText("1 .");
        jPanel1.add(jLabel_inven11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven59.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven59.setText("STS");
        jPanel4.add(jLabel_inven59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 10, 30, 30));

        jLabel_inven60.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven60.setText("No.");
        jPanel4.add(jLabel_inven60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel_inven61.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven61.setText("Pertanyaaan");
        jPanel4.add(jLabel_inven61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, 30));

        jLabel_inven62.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven62.setText("SS");
        jPanel4.add(jLabel_inven62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 30, 30));

        jLabel_inven63.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven63.setText("S");
        jPanel4.add(jLabel_inven63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 30, 30));

        jLabel_inven64.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven64.setText("KS");
        jPanel4.add(jLabel_inven64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 30, 30));

        jLabel_inven65.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven65.setText("TS");
        jPanel4.add(jLabel_inven65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 10, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1530, 50));

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven40.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven40.setText("6 .");
        jPanel5.add(jLabel_inven40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 33));

        jLabel_inven43.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven43.setText("Apakah rencana kerja penanganan resiko sistem aplikasi telah mengukur keamanan serta mengurangi munculnya resiko lainnya?");
        jPanel5.add(jLabel_inven43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1090, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1160, 40));

        jPanel9.setBackground(new java.awt.Color(0, 153, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven56.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven56.setText("Jumlah");
        jPanel9.add(jLabel_inven56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        test1.setBackground(new java.awt.Color(0, 204, 0));
        test1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test1.setText("0");
        test1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test1MouseMoved(evt);
            }
        });
        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test1MouseExited(evt);
            }
        });
        test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test1ActionPerformed(evt);
            }
        });
        jPanel9.add(test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 40, 40));

        test2.setBackground(new java.awt.Color(0, 204, 0));
        test2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test2.setText("0");
        test2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test2MouseMoved(evt);
            }
        });
        test2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test2MouseExited(evt);
            }
        });
        test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2ActionPerformed(evt);
            }
        });
        jPanel9.add(test2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 40));

        test3.setBackground(new java.awt.Color(0, 204, 0));
        test3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test3.setText("0");
        test3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test3MouseMoved(evt);
            }
        });
        test3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test3MouseExited(evt);
            }
        });
        test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test3ActionPerformed(evt);
            }
        });
        jPanel9.add(test3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 40, 40));

        test4.setBackground(new java.awt.Color(0, 204, 0));
        test4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test4.setText("0");
        test4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test4MouseMoved(evt);
            }
        });
        test4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test4MouseExited(evt);
            }
        });
        test4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test4ActionPerformed(evt);
            }
        });
        jPanel9.add(test4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, 40));

        test5.setBackground(new java.awt.Color(0, 204, 0));
        test5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test5.setText("0");
        test5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test5MouseMoved(evt);
            }
        });
        test5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test5MouseExited(evt);
            }
        });
        test5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test5ActionPerformed(evt);
            }
        });
        jPanel9.add(test5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 40, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 1520, 40));

        jPanel12.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven53.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven53.setText("Jumlah Pertanyaan");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("8");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 985, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_inven53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 1230, 40));

        jPanel13.setBackground(new java.awt.Color(0, 153, 51));

        jLabel_inven55.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven55.setText("Jumlah Nilai Jawaban");

        jpo.setBackground(new java.awt.Color(0, 204, 0));
        jpo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpo.setText("0");
        jpo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpoMouseMoved(evt);
            }
        });
        jpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpoMouseExited(evt);
            }
        });
        jpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 976, Short.MAX_VALUE)
                .addComponent(jpo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inven55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 1520, 40));

        cb11.setBackground(new java.awt.Color(0, 153, 102));
        cb11.setForeground(new java.awt.Color(255, 255, 0));
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        jPanel1.add(cb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 150, -1, -1));

        cb31.setBackground(new java.awt.Color(0, 153, 102));
        cb31.setForeground(new java.awt.Color(255, 255, 0));
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });
        jPanel1.add(cb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 150, -1, -1));

        cb21.setBackground(new java.awt.Color(0, 153, 102));
        cb21.setForeground(new java.awt.Color(255, 255, 0));
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });
        jPanel1.add(cb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 150, -1, -1));

        cb41.setBackground(new java.awt.Color(0, 153, 102));
        cb41.setForeground(new java.awt.Color(255, 255, 0));
        cb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb41ActionPerformed(evt);
            }
        });
        jPanel1.add(cb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 150, -1, -1));

        cb43.setBackground(new java.awt.Color(0, 153, 102));
        cb43.setForeground(new java.awt.Color(255, 255, 0));
        cb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb43ActionPerformed(evt);
            }
        });
        jPanel1.add(cb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 270, -1, -1));

        cb33.setBackground(new java.awt.Color(0, 153, 102));
        cb33.setForeground(new java.awt.Color(255, 255, 0));
        cb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb33ActionPerformed(evt);
            }
        });
        jPanel1.add(cb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 270, -1, -1));

        cb23.setBackground(new java.awt.Color(0, 153, 102));
        cb23.setForeground(new java.awt.Color(255, 255, 0));
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });
        jPanel1.add(cb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 270, -1, -1));

        cb13.setBackground(new java.awt.Color(0, 153, 102));
        cb13.setForeground(new java.awt.Color(255, 255, 0));
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });
        jPanel1.add(cb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 270, -1, -1));

        cb45.setBackground(new java.awt.Color(0, 153, 102));
        cb45.setForeground(new java.awt.Color(255, 255, 0));
        cb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb45ActionPerformed(evt);
            }
        });
        jPanel1.add(cb45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 360, -1, -1));

        cb35.setBackground(new java.awt.Color(0, 153, 102));
        cb35.setForeground(new java.awt.Color(255, 255, 0));
        cb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb35ActionPerformed(evt);
            }
        });
        jPanel1.add(cb35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 360, -1, -1));

        cb25.setBackground(new java.awt.Color(0, 153, 102));
        cb25.setForeground(new java.awt.Color(255, 255, 0));
        cb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb25ActionPerformed(evt);
            }
        });
        jPanel1.add(cb25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 360, -1, -1));

        cb15.setBackground(new java.awt.Color(0, 153, 102));
        cb15.setForeground(new java.awt.Color(255, 255, 0));
        cb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb15ActionPerformed(evt);
            }
        });
        jPanel1.add(cb15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 360, -1, -1));

        cb46.setBackground(new java.awt.Color(0, 153, 102));
        cb46.setForeground(new java.awt.Color(255, 255, 0));
        cb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb46ActionPerformed(evt);
            }
        });
        jPanel1.add(cb46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 410, -1, -1));

        cb36.setBackground(new java.awt.Color(0, 153, 102));
        cb36.setForeground(new java.awt.Color(255, 255, 0));
        cb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb36ActionPerformed(evt);
            }
        });
        jPanel1.add(cb36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 410, -1, -1));

        cb26.setBackground(new java.awt.Color(0, 153, 102));
        cb26.setForeground(new java.awt.Color(255, 255, 0));
        cb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb26ActionPerformed(evt);
            }
        });
        jPanel1.add(cb26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 410, -1, -1));

        cb16.setBackground(new java.awt.Color(0, 153, 102));
        cb16.setForeground(new java.awt.Color(255, 255, 0));
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });
        jPanel1.add(cb16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 410, -1, -1));

        cb44.setBackground(new java.awt.Color(0, 153, 102));
        cb44.setForeground(new java.awt.Color(255, 255, 0));
        cb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb44ActionPerformed(evt);
            }
        });
        jPanel1.add(cb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 310, -1, -1));

        cb34.setBackground(new java.awt.Color(0, 153, 102));
        cb34.setForeground(new java.awt.Color(255, 255, 0));
        cb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb34ActionPerformed(evt);
            }
        });
        jPanel1.add(cb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 310, -1, -1));

        cb24.setBackground(new java.awt.Color(0, 153, 102));
        cb24.setForeground(new java.awt.Color(255, 255, 0));
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });
        jPanel1.add(cb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 310, 20, -1));

        cb14.setBackground(new java.awt.Color(0, 153, 102));
        cb14.setForeground(new java.awt.Color(255, 255, 0));
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });
        jPanel1.add(cb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 310, -1, -1));

        cb42.setBackground(new java.awt.Color(0, 153, 102));
        cb42.setForeground(new java.awt.Color(255, 255, 0));
        cb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb42ActionPerformed(evt);
            }
        });
        jPanel1.add(cb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, -1, -1));

        cb32.setBackground(new java.awt.Color(0, 153, 102));
        cb32.setForeground(new java.awt.Color(255, 255, 0));
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });
        jPanel1.add(cb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 200, -1, -1));

        cb22.setBackground(new java.awt.Color(0, 153, 102));
        cb22.setForeground(new java.awt.Color(255, 255, 0));
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });
        jPanel1.add(cb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 200, -1, -1));

        cb12.setBackground(new java.awt.Color(0, 153, 102));
        cb12.setForeground(new java.awt.Color(255, 255, 0));
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });
        jPanel1.add(cb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        ipo.setBackground(new java.awt.Color(0, 204, 0));
        ipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipo.setText("0");
        ipo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ipoMouseMoved(evt);
            }
        });
        ipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ipoMouseExited(evt);
            }
        });
        ipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ipo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 660, 100, 40));

        jPanel11.setBackground(new java.awt.Color(102, 153, 0));

        test7.setBackground(new java.awt.Color(0, 204, 0));
        test7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        test7.setText("Results");
        test7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                test7MouseMoved(evt);
            }
        });
        test7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                test7MouseExited(evt);
            }
        });
        test7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(test7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(test7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 760, 430, 40));

        jButton10.setBackground(new java.awt.Color(152, 201, 45));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(21, 25, 28));
        jButton10.setText("NEXT");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 810, 190, 40));

        cb47.setBackground(new java.awt.Color(0, 153, 102));
        cb47.setForeground(new java.awt.Color(255, 255, 0));
        cb47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cb47MouseExited(evt);
            }
        });
        cb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb47ActionPerformed(evt);
            }
        });
        jPanel1.add(cb47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 460, -1, -1));

        cb37.setBackground(new java.awt.Color(0, 153, 102));
        cb37.setForeground(new java.awt.Color(255, 255, 0));
        cb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb37ActionPerformed(evt);
            }
        });
        jPanel1.add(cb37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 460, -1, -1));

        cb27.setBackground(new java.awt.Color(0, 153, 102));
        cb27.setForeground(new java.awt.Color(255, 255, 0));
        cb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb27ActionPerformed(evt);
            }
        });
        jPanel1.add(cb27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 460, -1, -1));

        cb17.setBackground(new java.awt.Color(0, 153, 102));
        cb17.setForeground(new java.awt.Color(255, 255, 0));
        cb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb17ActionPerformed(evt);
            }
        });
        jPanel1.add(cb17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 460, -1, -1));

        jPanel14.setBackground(new java.awt.Color(102, 153, 0));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("INDEKS =");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 660, 170, 40));

        jLabel_inven57.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven57.setForeground(new java.awt.Color(0, 153, 0));
        jLabel_inven57.setText("Maturity Level");
        jPanel1.add(jLabel_inven57, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 770, -1, -1));

        jLabel_inven6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven6.setText("Apakah Pengujian dasar elemen pada sistem aplikasi telah menjelaskan resiko dan hubungan sebab akibatnya?");
        jPanel1.add(jLabel_inven6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 1090, 50));

        jLabel_inven12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven12.setText("3 .");
        jPanel1.add(jLabel_inven12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 50));

        jPanel6.setBackground(new java.awt.Color(0, 153, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven44.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven44.setText("8 .");
        jPanel6.add(jLabel_inven44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 33));

        jLabel_inven45.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven45.setText(" melalui proses penentuan rencana strategi SI dan dalam pengawasan serta mekanisme evaluasi SI?");
        jPanel6.add(jLabel_inven45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1090, 30));

        jLabel_inven46.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven46.setText("Apakah Penilaian resiko sebagai suatu alat penting di dalam perancangan dan pengimplementasian pengendalian internal telah dilakukan ");
        jPanel6.add(jLabel_inven46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1110, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1160, 80));

        jPanel10.setBackground(new java.awt.Color(0, 153, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven47.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven47.setText("2 .");
        jPanel10.add(jLabel_inven47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 33));

        jLabel_inven48.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven48.setText("Lingkup dan batasan, serta metodologi yang akan digunakan?");
        jPanel10.add(jLabel_inven48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1090, 30));

        jLabel_inven49.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven49.setText("Apakah dalam menilai resiko sistem aplikasi telah dilakukan suatu pendekatan umum penilaian resiko aplikasi yang menentukan ruang ");
        jPanel10.add(jLabel_inven49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1090, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1160, 80));

        jLabel_inven7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven7.setText("Apakah ketentuan rencana kerja penanganan resiko sistem aplikasi telah memastikan pengendalian biaya yang efektif?");
        jPanel1.add(jLabel_inven7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 1090, 50));

        jLabel_inven13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven13.setText("5 .");
        jPanel1.add(jLabel_inven13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 50));

        jPanel15.setBackground(new java.awt.Color(0, 153, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven50.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven50.setText("4 .");
        jPanel15.add(jLabel_inven50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 33));

        jLabel_inven51.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven51.setText("Apakah resiko sistem aplikasi yang telah diuji dihasilkan dari suatu pengukuran kuantitatif atau kualitatif melalui analisis resiko?");
        jPanel15.add(jLabel_inven51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1090, 30));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1160, 40));

        jLabel_inven8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven8.setText("Akademi, faktor ketidakpastian dan faktor efektifitas biaya penerapan pengamanan sistem dan pengendalian internalnya?");
        jPanel1.add(jLabel_inven8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 1090, 50));

        jLabel_inven14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven14.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven14.setText("7 .");
        jPanel1.add(jLabel_inven14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 40, 50));

        jLabel_inven9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven9.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven9.setText("Apakah sisa resiko sistem aplikasi yang masih ada telah diterima dengan mempertimbangkan faktor efek dari resiko tersebut,faktor kebijakan");
        jPanel1.add(jLabel_inven9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 1160, 50));

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven52.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven52.setText("2 .");
        jPanel7.add(jLabel_inven52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 33));

        jLabel_inven54.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven54.setText("Lingkup dan batasan, serta metodologi yang akan digunakan?");
        jPanel7.add(jLabel_inven54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1090, 30));

        jLabel_inven58.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_inven58.setText("Apakah dalam menilai resiko sistem aplikasi telah dilakukan suatu pendekatan umum penilaian resiko aplikasi yang menentukan ruang ");
        jPanel7.add(jLabel_inven58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1090, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1140, 80));

        cb48.setBackground(new java.awt.Color(0, 153, 102));
        cb48.setForeground(new java.awt.Color(255, 255, 0));
        cb48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cb48MouseExited(evt);
            }
        });
        cb48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb48ActionPerformed(evt);
            }
        });
        jPanel1.add(cb48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 530, -1, -1));

        cb38.setBackground(new java.awt.Color(0, 153, 102));
        cb38.setForeground(new java.awt.Color(255, 255, 0));
        cb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb38ActionPerformed(evt);
            }
        });
        jPanel1.add(cb38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 530, -1, -1));

        cb28.setBackground(new java.awt.Color(0, 153, 102));
        cb28.setForeground(new java.awt.Color(255, 255, 0));
        cb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb28ActionPerformed(evt);
            }
        });
        jPanel1.add(cb28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 530, -1, -1));

        cb18.setBackground(new java.awt.Color(0, 153, 102));
        cb18.setForeground(new java.awt.Color(255, 255, 0));
        cb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb18ActionPerformed(evt);
            }
        });
        jPanel1.add(cb18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 530, -1, -1));

        cb51.setBackground(new java.awt.Color(0, 153, 102));
        cb51.setForeground(new java.awt.Color(255, 255, 0));
        cb51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb51ActionPerformed(evt);
            }
        });
        jPanel1.add(cb51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 150, -1, -1));

        cb52.setBackground(new java.awt.Color(0, 153, 102));
        cb52.setForeground(new java.awt.Color(255, 255, 0));
        cb52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb52ActionPerformed(evt);
            }
        });
        jPanel1.add(cb52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 200, -1, -1));

        cb53.setBackground(new java.awt.Color(0, 153, 102));
        cb53.setForeground(new java.awt.Color(255, 255, 0));
        cb53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb53ActionPerformed(evt);
            }
        });
        jPanel1.add(cb53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 270, -1, -1));

        cb54.setBackground(new java.awt.Color(0, 153, 102));
        cb54.setForeground(new java.awt.Color(255, 255, 0));
        cb54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb54ActionPerformed(evt);
            }
        });
        jPanel1.add(cb54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 310, -1, -1));

        cb55.setBackground(new java.awt.Color(0, 153, 102));
        cb55.setForeground(new java.awt.Color(255, 255, 0));
        cb55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb55ActionPerformed(evt);
            }
        });
        jPanel1.add(cb55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 360, -1, -1));

        cb56.setBackground(new java.awt.Color(0, 153, 102));
        cb56.setForeground(new java.awt.Color(255, 255, 0));
        cb56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb56ActionPerformed(evt);
            }
        });
        jPanel1.add(cb56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 410, -1, -1));

        cb57.setBackground(new java.awt.Color(0, 153, 102));
        cb57.setForeground(new java.awt.Color(255, 255, 0));
        cb57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cb57MouseExited(evt);
            }
        });
        cb57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb57ActionPerformed(evt);
            }
        });
        jPanel1.add(cb57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 460, -1, -1));

        cb58.setBackground(new java.awt.Color(0, 153, 102));
        cb58.setForeground(new java.awt.Color(255, 255, 0));
        cb58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cb58MouseExited(evt);
            }
        });
        cb58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb58ActionPerformed(evt);
            }
        });
        jPanel1.add(cb58, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
       if(cb11.isSelected()){
            cb11d=1;
            cb11.setSelected(true);
        }else{
            cb11d=0;
            cb11.setSelected(false);
        }
    }//GEN-LAST:event_cb11ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
          
        if(cb31.isSelected()){
            cb31b=1;
            cb31.setSelected(true);
        }else{
            cb31b=0;
            cb31.setSelected(false);
        }
    }//GEN-LAST:event_cb31ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
        if(cb21.isSelected()){
            cb21c=1;
            cb21.setSelected(true);
        }else{
            cb21c=0;
            cb21.setSelected(false);
        }
    }//GEN-LAST:event_cb21ActionPerformed

    private void cb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb41ActionPerformed
        
        if(cb41.isSelected()){
            cb41a=1;
            cb41.setSelected(true);
        }else{
            cb41a=0;
            cb41.setSelected(false);
        }
    }//GEN-LAST:event_cb41ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void cb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb43ActionPerformed
          if(cb43.isSelected()){
            cb43a=1;
            cb43.setSelected(true);
        }else{
            cb43a=0;
            cb43.setSelected(false);
        }
    }//GEN-LAST:event_cb43ActionPerformed

    private void cb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb33ActionPerformed
          if(cb33.isSelected()){
            cb33b=1;
            cb33.setSelected(true);
        }else{
            cb33b=0;
            cb33.setSelected(false);
        }
    }//GEN-LAST:event_cb33ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
            if(cb23.isSelected()){
            cb23c=1;
            cb23.setSelected(true);
        }else{
            cb23c=0;
            cb23.setSelected(false);
        }
    }//GEN-LAST:event_cb23ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
         if(cb13.isSelected()){
            cb13d=1;
            cb13.setSelected(true);
        }else{
            cb13d=0;
            cb13.setSelected(false);
        }
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb45ActionPerformed
        if(cb45.isSelected()){
            cb45a=1;
            cb45.setSelected(true);
        }else{
            cb45a=0;
            cb45.setSelected(false);
        }
    }//GEN-LAST:event_cb45ActionPerformed

    private void cb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb35ActionPerformed
          if(cb35.isSelected()){
            cb35b=1;
            cb35.setSelected(true);
        }else{
            cb35b=0;
            cb35.setSelected(false);
        }
    }//GEN-LAST:event_cb35ActionPerformed

    private void cb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb25ActionPerformed
             if(cb25.isSelected()){
            cb25c=1;
            cb25.setSelected(true);
        }else{
            cb25c=0;
            cb25.setSelected(false);
        }
    }//GEN-LAST:event_cb25ActionPerformed

    private void cb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb15ActionPerformed
         if(cb15.isSelected()){
            cb15d=1;
            cb15.setSelected(true);
        }else{
            cb15d=0;
            cb15.setSelected(false);
        }
    }//GEN-LAST:event_cb15ActionPerformed

    private void cb46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb46ActionPerformed
        if(cb46.isSelected()){
            cb46a=1;
            cb46.setSelected(true);
        }else{
            cb46a=0;
            cb46.setSelected(false);
        }
    }//GEN-LAST:event_cb46ActionPerformed

    private void cb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb36ActionPerformed
          if(cb36.isSelected()){
            cb36b=1;
            cb36.setSelected(true);
        }else{
            cb36b=0;
            cb36.setSelected(false);
        }
    }//GEN-LAST:event_cb36ActionPerformed

    private void cb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb26ActionPerformed
             if(cb26.isSelected()){
            cb26c=1;
            cb26.setSelected(true);
        }else{
            cb26c=0;
            cb26.setSelected(false);
        }
    }//GEN-LAST:event_cb26ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
         if(cb16.isSelected()){
            cb16d=1;
            cb16.setSelected(true);
        }else{
            cb16d=0;
            cb16.setSelected(false);
        }
    }//GEN-LAST:event_cb16ActionPerformed

    private void cb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb44ActionPerformed
         if(cb44.isSelected()){
            cb44a=1;
            cb44.setSelected(true);
        }else{
            cb44a=0;
            cb44.setSelected(false);
        }
    }//GEN-LAST:event_cb44ActionPerformed

    private void cb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb34ActionPerformed
         if(cb34.isSelected()){
            cb34b=1;
            cb34.setSelected(true);
        }else{
            cb34b=0;
            cb34.setSelected(false);
        }
    }//GEN-LAST:event_cb34ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
             if(cb24.isSelected()){
            cb24c=1;
            cb24.setSelected(true);
        }else{
            cb24c=0;
            cb24.setSelected(false);
        }
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
         if(cb14.isSelected()){
            cb14d=1;
            cb14.setSelected(true);
        }else{
            cb14d=0;
            cb14.setSelected(false);
        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb42ActionPerformed
         if(cb42.isSelected()){
            cb42a=1;
            cb42.setSelected(true);
        }else{
            cb42a=0;
            cb42.setSelected(false);
        }
    }//GEN-LAST:event_cb42ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
         if(cb32.isSelected()){
            cb32b=1;
            cb32.setSelected(true);
        }else{
            cb32b=0;
            cb32.setSelected(false);
        }
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        if(cb22.isSelected()){
            cb22c=1;
            cb22.setSelected(true);
        }else{
            cb22c=0;
            cb22.setSelected(false);
        }
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
         if(cb12.isSelected()){
            cb12d=1;
            cb12.setSelected(true);
        }else{
            cb12d=0;
            cb12.setSelected(false);
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        AI2 fa = new AI2(jpo.getText(),ipo.getText());
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cb47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb47ActionPerformed
        if(cb47.isSelected()){
            cb47a=1;
            cb47.setSelected(true);
        }else{
            cb47a=0;
            cb47.setSelected(false);
        }
    }//GEN-LAST:event_cb47ActionPerformed

    private void cb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb37ActionPerformed
          if(cb37.isSelected()){
            cb37b=1;
            cb37.setSelected(true);
        }else{
            cb37b=0;
            cb37.setSelected(false);
        }
    }//GEN-LAST:event_cb37ActionPerformed

    private void cb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb27ActionPerformed
             if(cb27.isSelected()){
            cb27c=1;
            cb27.setSelected(true);
        }else{
            cb27c=0;
            cb27.setSelected(false);
        }
    }//GEN-LAST:event_cb27ActionPerformed

    private void cb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb17ActionPerformed
         if(cb17.isSelected()){
            cb17d=1;
            cb17.setSelected(true);
        }else{
            cb17d=0;
            cb17.setSelected(false);
        }
    }//GEN-LAST:event_cb17ActionPerformed

    private void test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test1ActionPerformed
       
    }//GEN-LAST:event_test1ActionPerformed

    private void test1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseExited
     
        a = cb41a+cb42a+cb43a+cb44a+cb45a+cb46a+cb47a+cb48a;
        a1 = a * 4;
        
        test1.setText(Integer.toString(a));
    }//GEN-LAST:event_test1MouseExited

    private void test1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseMoved
        
    }//GEN-LAST:event_test1MouseMoved

    private void test2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test2MouseMoved

    private void test2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test2MouseExited
       int b;
        b = cb31b+cb32b+cb33b+cb34b+cb35b+cb36b+cb37b+cb38b;
        a2 = b*3;
        test2.setText(Integer.toString(b));
    }//GEN-LAST:event_test2MouseExited

    private void test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test2ActionPerformed

    private void test3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test3MouseMoved

    private void test3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test3MouseExited
        int c;
        c = cb21c+cb22c+cb23c+cb24c+cb25c+cb26c+cb27c+cb28c;
        a3=c*2;
        test3.setText(Integer.toString(c));
    }//GEN-LAST:event_test3MouseExited

    private void test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test3ActionPerformed

    private void test4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test4MouseMoved

    private void test4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test4MouseExited
         int d;
        d = cb11d+cb12d+cb13d+cb14d+cb15d+cb16d+cb17d+cb18d;
        a4 = d*1;
        test4.setText(Integer.toString(d));
    }//GEN-LAST:event_test4MouseExited

    private void test4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test4ActionPerformed

    private void jpoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jpoMouseMoved

    private void jpoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpoMouseExited
       
        
        e=a1+a2+a3+a4+a5;
        
        jpo.setText(Integer.toString(e));
    }//GEN-LAST:event_jpoMouseExited

    private void jpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpoActionPerformed
        
    }//GEN-LAST:event_jpoActionPerformed

    private void ipoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ipoMouseMoved

    private void ipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipoMouseExited
        DecimalFormat formatData = new DecimalFormat("#.##");
       double y;
       
       y=(double)e/8;
       
        f = Double.valueOf(formatData.format(y));
        ipo.setText(Double.toString(f));
        
        if (f < 0.5){
            test7.setText("Non Existent");
        }else{
            if(f >0.52 && f <1.5){
                test7.setText("Intial/Ad Hoc");
            }else{
                if(f >1.51 && f<2.5){
                    test7.setText("Repeatable but Intuitive");
                }else{
                    if(f>2.51 && f<3.50){
                        test7.setText("Defined Process");
                    }else{
                        if(f>3.51 && f<4.5){
                            test7.setText("Managed And Measurable");
                        }else{
                            if(f>4.51){
                                test7.setText("Optimized");
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_ipoMouseExited

    private void ipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipoActionPerformed

    private void test7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test7MouseMoved

    private void test7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test7MouseExited
        
    }//GEN-LAST:event_test7MouseExited

    private void test7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test7ActionPerformed

    private void cb48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb48ActionPerformed
         if(cb48.isSelected()){
            cb48a=1;
            cb48.setSelected(true);
        }else{
            cb48a=0;
            cb48.setSelected(false);
        }
    }//GEN-LAST:event_cb48ActionPerformed

    private void cb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb38ActionPerformed
       if(cb38.isSelected()){
            cb38b=1;
            cb38.setSelected(true);
        }else{
            cb38b=0;
            cb38.setSelected(false);
        }
    }//GEN-LAST:event_cb38ActionPerformed

    private void cb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb28ActionPerformed
         if(cb28.isSelected()){
            cb28c=1;
            cb28.setSelected(true);
        }else{
            cb28c=0;
            cb28.setSelected(false);
        }
    }//GEN-LAST:event_cb28ActionPerformed

    private void cb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb18ActionPerformed
        if(cb18.isSelected()){
            cb18d=1;
            cb18.setSelected(true);
        }else{
            cb18d=0;
            cb18.setSelected(false);
        }
    }//GEN-LAST:event_cb18ActionPerformed

    private void cb47MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb47MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cb47MouseExited

    private void cb48MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb48MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cb48MouseExited

    private void cb51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb51ActionPerformed
        if(cb51.isSelected()){
            cb51a=1;
            cb51.setSelected(true);
        }else{
            cb51a=0;
            cb51.setSelected(false);
        }
    }//GEN-LAST:event_cb51ActionPerformed

    private void cb52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb52ActionPerformed
        if(cb52.isSelected()){
            cb52a=1;
            cb52.setSelected(true);
        }else{
            cb52a=0;
            cb52.setSelected(false);
        }
    }//GEN-LAST:event_cb52ActionPerformed

    private void cb53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb53ActionPerformed
         if(cb53.isSelected()){
            cb53a=1;
            cb53.setSelected(true);
        }else{
            cb53a=0;
            cb53.setSelected(false);
        }
    }//GEN-LAST:event_cb53ActionPerformed

    private void cb54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb54ActionPerformed
         if(cb54.isSelected()){
            cb54a=1;
            cb54.setSelected(true);
        }else{
            cb54a=0;
            cb54.setSelected(false);
        }
    }//GEN-LAST:event_cb54ActionPerformed

    private void cb55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb55ActionPerformed
        if(cb55.isSelected()){
            cb55a=1;
            cb55.setSelected(true);
        }else{
            cb55a=0;
            cb55.setSelected(false);
        }
    }//GEN-LAST:event_cb55ActionPerformed

    private void cb56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb56ActionPerformed
         if(cb56.isSelected()){
            cb56a=1;
            cb56.setSelected(true);
        }else{
            cb56a=0;
            cb56.setSelected(false);
        }
    }//GEN-LAST:event_cb56ActionPerformed

    private void cb57MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb57MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cb57MouseExited

    private void cb57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb57ActionPerformed
       if(cb57.isSelected()){
            cb57a=1;
            cb57.setSelected(true);
        }else{
            cb57a=0;
            cb57.setSelected(false);
        }
    }//GEN-LAST:event_cb57ActionPerformed

    private void cb58MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb58MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cb58MouseExited

    private void cb58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb58ActionPerformed
        if(cb58.isSelected()){
            cb58a=1;
            cb58.setSelected(true);
        }else{
            cb58a=0;
            cb58.setSelected(false);
        }
    }//GEN-LAST:event_cb58ActionPerformed

    private void test5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_test5MouseMoved

    private void test5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test5MouseExited
        g = cb51a+cb52a+cb53a+cb54a+cb55a+cb56a+cb57a+cb58a;
        a5 = g * 5;
        
        test5.setText(Integer.toString(g));
    }//GEN-LAST:event_test5MouseExited

    private void test5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PO9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PO9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PO9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PO9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PO9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb17;
    private javax.swing.JCheckBox cb18;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb25;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb27;
    private javax.swing.JCheckBox cb28;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb33;
    private javax.swing.JCheckBox cb34;
    private javax.swing.JCheckBox cb35;
    private javax.swing.JCheckBox cb36;
    private javax.swing.JCheckBox cb37;
    private javax.swing.JCheckBox cb38;
    private javax.swing.JCheckBox cb41;
    private javax.swing.JCheckBox cb42;
    private javax.swing.JCheckBox cb43;
    private javax.swing.JCheckBox cb44;
    private javax.swing.JCheckBox cb45;
    private javax.swing.JCheckBox cb46;
    private javax.swing.JCheckBox cb47;
    private javax.swing.JCheckBox cb48;
    private javax.swing.JCheckBox cb51;
    private javax.swing.JCheckBox cb52;
    private javax.swing.JCheckBox cb53;
    private javax.swing.JCheckBox cb54;
    private javax.swing.JCheckBox cb55;
    private javax.swing.JCheckBox cb56;
    private javax.swing.JCheckBox cb57;
    private javax.swing.JCheckBox cb58;
    private javax.swing.JTextField ipo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel_inven11;
    private javax.swing.JLabel jLabel_inven12;
    private javax.swing.JLabel jLabel_inven13;
    private javax.swing.JLabel jLabel_inven14;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven40;
    private javax.swing.JLabel jLabel_inven43;
    private javax.swing.JLabel jLabel_inven44;
    private javax.swing.JLabel jLabel_inven45;
    private javax.swing.JLabel jLabel_inven46;
    private javax.swing.JLabel jLabel_inven47;
    private javax.swing.JLabel jLabel_inven48;
    private javax.swing.JLabel jLabel_inven49;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JLabel jLabel_inven50;
    private javax.swing.JLabel jLabel_inven51;
    private javax.swing.JLabel jLabel_inven52;
    private javax.swing.JLabel jLabel_inven53;
    private javax.swing.JLabel jLabel_inven54;
    private javax.swing.JLabel jLabel_inven55;
    private javax.swing.JLabel jLabel_inven56;
    private javax.swing.JLabel jLabel_inven57;
    private javax.swing.JLabel jLabel_inven58;
    private javax.swing.JLabel jLabel_inven59;
    private javax.swing.JLabel jLabel_inven6;
    private javax.swing.JLabel jLabel_inven60;
    private javax.swing.JLabel jLabel_inven61;
    private javax.swing.JLabel jLabel_inven62;
    private javax.swing.JLabel jLabel_inven63;
    private javax.swing.JLabel jLabel_inven64;
    private javax.swing.JLabel jLabel_inven65;
    private javax.swing.JLabel jLabel_inven7;
    private javax.swing.JLabel jLabel_inven8;
    private javax.swing.JLabel jLabel_inven9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jpo;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label8;
    private javax.swing.JTextField test1;
    private javax.swing.JTextField test2;
    private javax.swing.JTextField test3;
    private javax.swing.JTextField test4;
    private javax.swing.JTextField test5;
    private javax.swing.JTextField test7;
    // End of variables declaration//GEN-END:variables
}
