/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package auditapp;


import java.awt.Color;
import static java.awt.Color.BLUE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Yaseen Ameer
 */
public class RID extends javax.swing.JFrame {
   
    private String tgl;
    

    /**
     * Creates new form NewSignin
     */
    public RID(String jds, String ids, String x1, String x2, String x3, String x4, String x5, String x6) {
        
        koneksi_database();
       
        initComponents();
        this.setLocationRelativeTo(null);
      
         try {
          
              UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        
        }
        
        catch (Exception ex) {
            System.err.println(ex);
        }
         jn1.setText(x5);
         j1.setText(x6);
         
         jn2.setText(x3);
         j2.setText(x4);
        
         jn3.setText(x1);
         j3.setText(x2);
         
         jn4.setText(jds);
         j4.setText(ids);
        
         
        double a = Double.parseDouble(j1.getText());
        double b = Double.parseDouble(j2.getText());
        double c = Double.parseDouble(j3.getText());
        double d = Double.parseDouble(j4.getText());
        
        DecimalFormat formatData = new DecimalFormat("#.##");
        double z;
         
        z = ((double)a + b + c + d)/4;
        
        double z1;
        
        z1 = Double.valueOf(formatData.format(z));
        rata.setText(Double.toString(z1));
        rata1.setText(Double.toString(z1));
       
        
        if (z < 0.5){
            tm.setText("Non Existent");
            tm1.setText("Non Existent");
        }else{
            if(z >=0.52 && z <=1.5){
                tm.setText("Intial/Ad Hoc");
                tm1.setText("Intial/Ad Hoc");
            }else{
                if(z >=1.51 && z<=2.5){
                    tm.setText("Repeatable but Intuitive");
                    tm1.setText("Repeatable but Intuitive");
                }else{
                    if(z>=2.51 && z<=3.50){
                        tm.setText("Defined Process");
                        tm1.setText("Defined Process");
                    }else{
                        if(z>=3.51 && z<=4.5){
                            tm.setText("Managed And Measurable");
                            tm1.setText("Managed And Measurable");
                        }else{
                            if(z>4.51){
                                tm.setText("Optimized");
                                tm1.setText("Optimized");
                            }
                        }
                    }
                }
            }
        }
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel_inven2 = new javax.swing.JLabel();
        jLabel_inven10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_inven21 = new javax.swing.JLabel();
        rata = new javax.swing.JTextField();
        tm = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel_inven16 = new javax.swing.JLabel();
        jLabel_inven22 = new javax.swing.JLabel();
        jLabel_inven23 = new javax.swing.JLabel();
        jLabel_inven24 = new javax.swing.JLabel();
        jLabel_inven25 = new javax.swing.JLabel();
        jLabel_inven26 = new javax.swing.JLabel();
        jLabel_inven27 = new javax.swing.JLabel();
        jLabel_inven28 = new javax.swing.JLabel();
        jLabel_inven29 = new javax.swing.JLabel();
        jLabel_inven30 = new javax.swing.JLabel();
        jLabel_inven31 = new javax.swing.JLabel();
        jn1 = new javax.swing.JTextField();
        jn4 = new javax.swing.JTextField();
        jn3 = new javax.swing.JTextField();
        jn2 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel_inven6 = new javax.swing.JLabel();
        jLabel_inven32 = new javax.swing.JLabel();
        jLabel_inven33 = new javax.swing.JLabel();
        jLabel_inven34 = new javax.swing.JLabel();
        jLabel_inven35 = new javax.swing.JLabel();
        jLabel_inven36 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel_inven37 = new javax.swing.JLabel();
        jLabel_inven38 = new javax.swing.JLabel();
        rata1 = new javax.swing.JTextField();
        tm1 = new javax.swing.JTextField();
        jLabel_inven39 = new javax.swing.JLabel();
        kode_audit = new javax.swing.JTextField();
        jLabel_inven40 = new javax.swing.JLabel();
        tgl_audit = new com.toedter.calendar.JDateChooser();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 0, 620));

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("Rata - rata Indeks Domain");
        jPanel1.add(jLabel_inven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, 50));

        jLabel_inven10.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven10.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven10.setText("ME2");
        jPanel1.add(jLabel_inven10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 50, 50));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven21.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven21.setText("Rata - rata Indeks");
        jPanel2.add(jLabel_inven21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 50));

        rata.setBackground(new java.awt.Color(0, 204, 0));
        rata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rata.setText("0");
        rata.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rataMouseMoved(evt);
            }
        });
        rata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rataMouseExited(evt);
            }
        });
        rata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rataActionPerformed(evt);
            }
        });
        jPanel2.add(rata, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 80, 50));

        tm.setBackground(new java.awt.Color(0, 204, 0));
        tm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm.setText("0");
        tm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tmMouseMoved(evt);
            }
        });
        tm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tmMouseExited(evt);
            }
        });
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        jPanel2.add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 380, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1180, 50));

        jButton9.setBackground(new java.awt.Color(152, 201, 45));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(21, 25, 28));
        jButton9.setText("Proses");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 700, 190, 40));

        jLabel_inven16.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven16.setText("4");
        jPanel1.add(jLabel_inven16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 30, 50));

        jLabel_inven22.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven22.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven22.setText("10");
        jPanel1.add(jLabel_inven22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 30, 50));

        jLabel_inven23.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven23.setText("2");
        jPanel1.add(jLabel_inven23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 30, 50));

        jLabel_inven24.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven24.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven24.setText("3");
        jPanel1.add(jLabel_inven24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 30, 50));

        jLabel_inven25.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven25.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven25.setText("PO9");
        jPanel1.add(jLabel_inven25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, 50));

        jLabel_inven26.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven26.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven26.setText("AI2");
        jPanel1.add(jLabel_inven26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 50, 50));

        jLabel_inven27.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven27.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven27.setText("Artinya System E-Raport Pada SMA N 8 Padang berada pada Tingkat");
        jPanel1.add(jLabel_inven27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 750, 50));

        jLabel_inven28.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven28.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven28.setText("Tanggal Audit");
        jPanel1.add(jLabel_inven28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 50));

        jLabel_inven29.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven29.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven29.setText("8");
        jPanel1.add(jLabel_inven29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 30, 50));

        jLabel_inven30.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven30.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven30.setText("7");
        jPanel1.add(jLabel_inven30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 30, 50));

        jLabel_inven31.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven31.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven31.setText("4");
        jPanel1.add(jLabel_inven31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 30, 50));

        jn1.setBackground(new java.awt.Color(0, 204, 0));
        jn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jn1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jn1.setText("0");
        jn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jn1MouseMoved(evt);
            }
        });
        jn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jn1MouseExited(evt);
            }
        });
        jn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 50, -1));

        jn4.setBackground(new java.awt.Color(0, 204, 0));
        jn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jn4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jn4.setText("0");
        jn4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jn4MouseMoved(evt);
            }
        });
        jn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jn4MouseExited(evt);
            }
        });
        jn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 50, -1));

        jn3.setBackground(new java.awt.Color(0, 204, 0));
        jn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jn3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jn3.setText("0");
        jn3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jn3MouseMoved(evt);
            }
        });
        jn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jn3MouseExited(evt);
            }
        });
        jn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 50, -1));

        jn2.setBackground(new java.awt.Color(0, 204, 0));
        jn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jn2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jn2.setText("0");
        jn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jn2MouseMoved(evt);
            }
        });
        jn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jn2MouseExited(evt);
            }
        });
        jn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 50, -1));

        j1.setBackground(new java.awt.Color(0, 204, 0));
        j1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1.setText("0");
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j1MouseExited(evt);
            }
        });
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        jPanel1.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 50, -1));

        j3.setBackground(new java.awt.Color(0, 204, 0));
        j3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.setText("0");
        j3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j3MouseMoved(evt);
            }
        });
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j3MouseExited(evt);
            }
        });
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        jPanel1.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 50, -1));

        j2.setBackground(new java.awt.Color(0, 204, 0));
        j2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setText("0");
        j2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j2MouseMoved(evt);
            }
        });
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j2MouseExited(evt);
            }
        });
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        jPanel1.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 50, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_inven6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven6.setText("Tingkat Model Maturity");
        jPanel4.add(jLabel_inven6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 290, 50));

        jLabel_inven32.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven32.setText("Proses");
        jPanel4.add(jLabel_inven32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 80, 50));

        jLabel_inven33.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven33.setText("No.");
        jPanel4.add(jLabel_inven33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel_inven34.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven34.setText("Jumlah Pertanyaan");
        jPanel4.add(jLabel_inven34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 220, 50));

        jLabel_inven35.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven35.setText("Jumlah Nilai Jawaban");
        jPanel4.add(jLabel_inven35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 260, 50));

        jLabel_inven36.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven36.setText("Indeks");
        jPanel4.add(jLabel_inven36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 90, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1180, 50));

        j4.setBackground(new java.awt.Color(0, 204, 0));
        j4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.setText("0");
        j4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j4MouseMoved(evt);
            }
        });
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                j4MouseExited(evt);
            }
        });
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        jPanel1.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 50, -1));

        jLabel_inven37.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven37.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven37.setText("DS5");
        jPanel1.add(jLabel_inven37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 50, 50));

        jLabel_inven38.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven38.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven38.setText("Untuk Posisi level maturity system pada E-raport SMA 8 Padang berada pada level");
        jPanel1.add(jLabel_inven38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 890, 50));

        rata1.setBackground(new java.awt.Color(0, 204, 0));
        rata1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rata1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rata1.setText("0");
        rata1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rata1MouseMoved(evt);
            }
        });
        rata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rata1MouseExited(evt);
            }
        });
        rata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rata1ActionPerformed(evt);
            }
        });
        jPanel1.add(rata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 90, 30));

        tm1.setBackground(new java.awt.Color(0, 204, 0));
        tm1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tm1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1.setText("0");
        tm1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tm1MouseMoved(evt);
            }
        });
        tm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tm1MouseExited(evt);
            }
        });
        tm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm1ActionPerformed(evt);
            }
        });
        jPanel1.add(tm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 370, 30));

        jLabel_inven39.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven39.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven39.setText("1");
        jPanel1.add(jLabel_inven39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 50));

        kode_audit.setBackground(new java.awt.Color(0, 204, 0));
        kode_audit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kode_audit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kode_audit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                kode_auditMouseMoved(evt);
            }
        });
        kode_audit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kode_auditMouseExited(evt);
            }
        });
        kode_audit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_auditActionPerformed(evt);
            }
        });
        jPanel1.add(kode_audit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, 30));

        jLabel_inven40.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven40.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven40.setText("Kode Audit");
        jPanel1.add(jLabel_inven40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 50));

        tgl_audit.setBackground(new java.awt.Color(0, 0, 0));
        tgl_audit.setForeground(new java.awt.Color(0, 204, 0));
        tgl_audit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_auditPropertyChange(evt);
            }
        });
        jPanel1.add(tgl_audit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 150, 30));

        jButton10.setBackground(new java.awt.Color(152, 201, 45));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(21, 25, 28));
        jButton10.setText("Diagram");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 700, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       try {
            sql = "INSERT INTO data_audit VALUES ('"+kode_audit.getText()+
            "','"+tgl+
            "','"+j1.getText()+
            "','"+j2.getText()+
            "','"+j3.getText()+
            "','"+j4.getText()+
            "','"+rata.getText()+
            "','"+tm.getText()+       
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Data Audit Pada Tanggal " + tgl + " Telah Tersimpan ");
            
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }
       
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jn1MouseMoved

    private void jn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn1MouseExited

       
    }//GEN-LAST:event_jn1MouseExited

    private void jn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jn1ActionPerformed

    }//GEN-LAST:event_jn1ActionPerformed

    private void jn4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jn4MouseMoved

    private void jn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jn4MouseExited

    private void jn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jn4ActionPerformed

    private void jn3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jn3MouseMoved

    private void jn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jn3MouseExited

    private void jn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jn3ActionPerformed

    private void jn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jn2MouseMoved

    private void jn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jn2MouseExited

    private void jn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jn2ActionPerformed

    private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j1MouseMoved

    private void j1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_j1MouseExited

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j4MouseMoved

    private void j4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_j4MouseExited

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void j3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j3MouseMoved

    private void j3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_j3MouseExited

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j2MouseMoved

    private void j2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_j2MouseExited

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void tmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tmMouseMoved

    private void tmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tmMouseExited

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void rataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rataMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rataMouseMoved

    private void rataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rataMouseExited
        
       
    }//GEN-LAST:event_rataMouseExited

    private void rataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rataActionPerformed

    private void rata1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rata1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rata1MouseMoved

    private void rata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rata1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rata1MouseExited

    private void rata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rata1ActionPerformed

    private void tm1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tm1MouseMoved

    private void tm1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tm1MouseExited

    private void tm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tm1ActionPerformed

    private void kode_auditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kode_auditMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_auditMouseMoved

    private void kode_auditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kode_auditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_auditMouseExited

    private void kode_auditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_auditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_auditActionPerformed

    private void tgl_auditPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_auditPropertyChange
        if(tgl_audit.getDate()!=null){
            SimpleDateFormat format_tanggal = new  SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tanggal.format(tgl_audit.getDate());
      }
    }//GEN-LAST:event_tgl_auditPropertyChange

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String a=j1.getText();
        String b=j2.getText();
        String c=j3.getText();
        String d=j4.getText();
        
        
        
        DefaultCategoryDataset piedata=new DefaultCategoryDataset();
        piedata.setValue(new Double(a), "Nilai Indeks", "PO9");
        piedata.setValue(new Double(b), "Nilai Indeks", "AI2");
        piedata.setValue(new Double(c), "Nilai Indeks", "ME2");
        piedata.setValue(new Double(d), "Nilai Indeks", "DS5");
       
        
        JFreeChart chart =ChartFactory.createBarChart("Grafik Hasil Indeks","X","Y",piedata);
        chart.setBackgroundPaint(Color.GREEN);
        chart.getTitle().setPaint(Color.BLACK);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame =new ChartFrame ("framechart",chart);
        frame.setVisible(true);
        frame.setBounds(500, 200, 500, 500);
      
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel_inven10;
    private javax.swing.JLabel jLabel_inven16;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven21;
    private javax.swing.JLabel jLabel_inven22;
    private javax.swing.JLabel jLabel_inven23;
    private javax.swing.JLabel jLabel_inven24;
    private javax.swing.JLabel jLabel_inven25;
    private javax.swing.JLabel jLabel_inven26;
    private javax.swing.JLabel jLabel_inven27;
    private javax.swing.JLabel jLabel_inven28;
    private javax.swing.JLabel jLabel_inven29;
    private javax.swing.JLabel jLabel_inven30;
    private javax.swing.JLabel jLabel_inven31;
    private javax.swing.JLabel jLabel_inven32;
    private javax.swing.JLabel jLabel_inven33;
    private javax.swing.JLabel jLabel_inven34;
    private javax.swing.JLabel jLabel_inven35;
    private javax.swing.JLabel jLabel_inven36;
    private javax.swing.JLabel jLabel_inven37;
    private javax.swing.JLabel jLabel_inven38;
    private javax.swing.JLabel jLabel_inven39;
    private javax.swing.JLabel jLabel_inven40;
    private javax.swing.JLabel jLabel_inven6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jn1;
    private javax.swing.JTextField jn2;
    private javax.swing.JTextField jn3;
    private javax.swing.JTextField jn4;
    private javax.swing.JTextField kode_audit;
    private javax.swing.JTextField rata;
    private javax.swing.JTextField rata1;
    private com.toedter.calendar.JDateChooser tgl_audit;
    private javax.swing.JTextField tm;
    private javax.swing.JTextField tm1;
    // End of variables declaration//GEN-END:variables

private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Ditemukan...");
       try {
           String url = "jdbc:mysql://localhost:3306/db_audit?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Terkoneksi.....");
           
       } catch (SQLException e){
           System.err.println("Tidak Terkoneksi.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Tidak Ditemukan.......");
   }
}


}
